# Stack name: windows-cf-eips-
AWSTemplateFormatVersion: 2010-09-09
Description: "Windows: Elastic IPs"

Parameters:

  WindowsEnvironmentType:
    Type: String

Resources:

  WindowsManagementEip:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Join [ "-", [!Ref AWS::StackName,!Ref WindowsEnvironmentType,"eip-management"]]

Outputs:

  WindowsEipManagementAllocationId:
    Description: Management AllocationId
    Value: !GetAtt WindowsManagementEip.AllocationId
    Export:
      Name: !Join [ "-", [!Ref AWS::StackName,"cf-eips",!Ref WindowsEnvironmentType,"WindowsEipManagementAllocationId"]]