# Stack name: linux-cf-main-
AWSTemplateFormatVersion: '2010-09-09'
Description: "Linux: root template"

Metadata:
  References:
    Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html

# Notes:
#     - By default linux-cf-tweak.yml make modifications to security groups to allow TCP 80 and 443.
#     - The Linux distribution can be edited in linux-cf-instances.yml (default Kali).

# Structure:
# - Parameters
# - Mappings
# - Resources
#   - linux-cf-eips
#     - Outputs
#   - linux-cf-l3
#     - Outputs
#   - linux-cf-sgs
#     - Outputs
#   - linux-cf-instances
#     - Outputs
#   - linux-cf-tweak
#     - Outputs
# - Outputs

Parameters:

  LinuxEnvironmentType:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Choose dev, test or prod. Default is dev.

  LinuxSecurityGroupIngressManagementIp:
    Type: String
    Default: 127.0.0.1/32
    AllowedPattern: ^(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\/(\b[12][0-9]?|\b3[0-2]|\b[0-9])$
    Description: Enter the primary management IP. Extra IP addresses can be added in linux-cf-tweak.yml.

  LinuxManagementSshKey:
    Type: String
    Default: c2-ok
    Description: The SSH key used to access the instances.

  # LinuxBaseS3Url = https://linux-cloudformation.s3.eu-central-1.amazonaws.com
  # Description: Base URL with templates from an S3 bucket
  LinuxTemplateEips:
    Type: String
    # Default: LinuxBaseS3Url/linux-cf-eips.yml
    Default: "https://linux-cloudformation.s3.eu-central-1.amazonaws.com/linux-cf-eips.yml"
    AllowedPattern: ^https\:\/\/(s3-|s3\.)?(.*)\.amazonaws\.com\/.*$
    Description: Enter location of file containing the template body. The URL must point to a template that's located in an Amazon S3 bucket. 

  LinuxTemplateL3:
    Type: String
    # Default: LinuxBaseS3Url/linux-cf-l3.yml
    Default: "https://linux-cloudformation.s3.eu-central-1.amazonaws.com/linux-cf-l3.yml"
    AllowedPattern: ^https\:\/\/(s3-|s3\.)?(.*)\.amazonaws\.com\/.*$
    Description: Enter location of file containing the template body. The URL must point to a template that's located in an Amazon S3 bucket. 

  LinuxTemplateSgs:
    Type: String
    # Default: LinuxBaseS3Url/linux-cf-sgs.yml
    Default: "https://linux-cloudformation.s3.eu-central-1.amazonaws.com/linux-cf-sgs.yml"
    AllowedPattern: ^https\:\/\/(s3-|s3\.)?(.*)\.amazonaws\.com\/.*$
    Description: Enter location of file containing the template body. The URL must point to a template that's located in an Amazon S3 bucket. 

  LinuxTemplateInstances:
    Type: String
    # Default: LinuxBaseS3Url/linux-cf-instances.yml
    Default: "https://linux-cloudformation.s3.eu-central-1.amazonaws.com/linux-cf-instances.yml"
    AllowedPattern: ^https\:\/\/(s3-|s3\.)?(.*)\.amazonaws\.com\/.*$
    Description: Enter location of file containing the template body. The URL must point to a template that's located in an Amazon S3 bucket. 

  LinuxTemplateTweak:
    Type: String
    # Default: LinuxBaseS3Url/linux-cf-tweak-stb.yml
    Default: "https://linux-cloudformation.s3.eu-central-1.amazonaws.com/linux-cf-tweak-stb.yml"
    AllowedPattern: ^https\:\/\/(s3-|s3\.)?(.*)\.amazonaws\.com\/.*$
    Description: Enter location of file containing the template body. The URL must point to a template that's located in an Amazon S3 bucket.

Resources:

  LinuxCfEips:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LinuxTemplateEips
      Parameters:
        LinuxEnvironmentType: !Ref LinuxEnvironmentType

  LinuxCfL3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LinuxTemplateL3
      Parameters:
        LinuxEnvironmentType: !Ref LinuxEnvironmentType

  LinuxCfSgs:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LinuxTemplateSgs
      Parameters:
        LinuxEnvironmentType: !Ref LinuxEnvironmentType
        LinuxSecurityGroupIngressManagementIp: !Ref LinuxSecurityGroupIngressManagementIp
        LinuxVpcVpcId: !GetAtt [LinuxCfL3, Outputs.LinuxVpcVpcId]

  LinuxCfInstances:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LinuxTemplateInstances
      Parameters:
        LinuxEnvironmentType: !Ref LinuxEnvironmentType
        LinuxManagementSshKey: !Ref LinuxManagementSshKey
        LinuxEipManagementAllocationId: !GetAtt [LinuxCfEips, Outputs.LinuxEipManagementAllocationId]
        LinuxSubManagementSubnetId: !GetAtt [LinuxCfL3, Outputs.LinuxSubManagementSubnetId]
        LinuxManagementSecurityGroupId: !GetAtt [LinuxCfSgs, Outputs.LinuxManagementSecurityGroupId]

  LinuxCfTweak:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LinuxTemplateTweak
      Parameters:
        LinuxEnvironmentType: !Ref LinuxEnvironmentType
        LinuxManagementSecurityGroupId: !GetAtt [LinuxCfSgs, Outputs.LinuxManagementSecurityGroupId]
        WindowsSecurityGroupIngressManagementIp: !Ref WindowsSecurityGroupIngressManagementIp

Outputs:

  LinuxManagementInstancePublicIp:
    Description: Public IP of the Linux server
    Value: !GetAtt [LinuxCfInstances, Outputs.LinuxManagementInstancePublicIp]
    
