# Stack name: windows-cf-instances-
Description: "Windows: Instances"

Parameters:

  WindowsEnvironmentType:
    Type: String

  WindowsManagementSshKey:
    Type: String

  WindowsEipManagementAllocationId:
    Type: String

  WindowsSubManagementSubnetId:
    Type: String

  WindowsManagementSecurityGroupId:
    Type: String

  # Ref: https://aws.amazon.com/blogs/mt/query-for-the-latest-windows-ami-using-systems-manager-parameter-store/
  # aws ec2 describe-images --owners amazon --filters "Name=name,Values=Windows_Server*" --query 'sort_by(Images, &CreationDate)[].Name' | grep 'Windows_Server-2022-English-Full-Base-'
  LatestWindowsServer2022AmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-windows-latest/Windows_Server-2022-English-Full-Base'

Mappings:

  Instances:
    management:
      name: "management"
      az: "0"
      InstanceType: "t3.medium"

Resources:
  
  WindowsManagementInstance:
    Type: AWS::EC2::Instance
    Properties:
      # Windows 11
      # Latest AMI ID can be found in GUI (EC2 -> AMI Catalog -> AWS Marketplace AMIs -> "Windows 11")
      # ImageId: ami-00e7b687bdab2b8ce
      ImageId: !Ref LatestWindowsServer2022AmiId
      InstanceType: !FindInMap [Instances, management, InstanceType]
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            Encrypted: true
            VolumeSize: 80
            DeleteOnTermination: true
      KeyName: !Ref WindowsManagementSshKey
      AvailabilityZone: !Select [ !FindInMap [Instances, management, az], !GetAZs ]
      Tags: 
        - Key: "Name"
          Value: !Join [ "-", [!Ref AWS::StackName,!Ref WindowsEnvironmentType,!FindInMap [Instances, management, name],!Select [ !FindInMap [Instances, management, az], !GetAZs ]]]
      SubnetId: !Ref WindowsSubManagementSubnetId
      SecurityGroupIds:
        - !Ref WindowsManagementSecurityGroupId

# EIP associations

  WindowsAssociateEipManagementInstance:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !Ref WindowsEipManagementAllocationId
      InstanceId: !Ref WindowsManagementInstance

Outputs:

  # Instance IP addresses

  WindowsManagementInstancePublicIp:
    Description: Management public IP address
    Value: !GetAtt WindowsManagementInstance.PublicIp
    Export:
      Name: !Join [ "-", [!Ref AWS::StackName,"cf-instances",!Ref WindowsEnvironmentType,"WindowsManagementInstancePublicIp"]]