# Stack name: linux-cf-instances-
Description: "Linux: Instances"

Parameters:

  LinuxEnvironmentType:
    Type: String

  LinuxManagementSshKey:
    Type: String

  LinuxEipManagementAllocationId:
    Type: String

  LinuxSubManagementSubnetId:
    Type: String

  LinuxManagementSecurityGroupId:
    Type: String

Mappings:

  Instances:
    management:
      name: "management"
      az: "0"
      InstanceType: "t3.medium"

Resources:
  
  LinuxManagementInstance:
    Type: AWS::EC2::Instance
    Properties:
      # Kali Linux kali-last-snapshot (2023.4.0)
      # Latest AMI ID can be found in GUI (EC2 -> AMIs -> Public images -> "kali-last-snapshot")
      ImageId: ami-084b4d9ebbfd1e08a
      InstanceType: !FindInMap [Instances, management, InstanceType]
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            Encrypted: true
            VolumeSize: 80
            DeleteOnTermination: true
      KeyName: !Ref LinuxManagementSshKey
      AvailabilityZone: !Select [ !FindInMap [Instances, management, az], !GetAZs ]
      Tags: 
        - Key: "Name"
          Value: !Join [ "-", ["linux",!Ref LinuxEnvironmentType,!FindInMap [Instances, management, name],!Select [ !FindInMap [Instances, management, az], !GetAZs ]]]
      SubnetId: !Ref LinuxSubManagementSubnetId
      SecurityGroupIds:
        - !Ref LinuxManagementSecurityGroupId

# EIP associations

  LinuxAssociateEipManagementInstance:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !Ref LinuxEipManagementAllocationId
      InstanceId: !Ref LinuxManagementInstance

Outputs:

  # Instance IP addresses

  LinuxManagementInstancePublicIp:
    Description: Management public IP address
    Value: !GetAtt LinuxManagementInstance.PublicIp
    Export:
      Name: !Join [ "-", ["linux-cf-instances",!Ref LinuxEnvironmentType,"LinuxManagementInstancePublicIp"]]