# Stack name: linux-cf-sgs-tweak-
AWSTemplateFormatVersion: 2010-09-09
Description: "Linux: Layer 3"

Metadata:
  References:
    Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elinux-security-group-ingress.html

Parameters:

  LinuxEnvironmentType:
    Type: String

  LinuxManagementSecurityGroupId:
    Type: String

  LinuxSecurityGroupIngressManagementIp:
    Type: String

Resources:

  # LinuxManagementSecurityGroup
  
  LinuxManagementSecurityGroupIngressRule1:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref LinuxManagementSecurityGroupId
      CidrIp: !Ref LinuxSecurityGroupIngressManagementIp
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
