# Stack name: linux-cf-eips-
AWSTemplateFormatVersion: 2010-09-09
Description: "Linux: Elastic IPs"

Parameters:

  LinuxEnvironmentType:
    Type: String

Resources:

  LinuxManagementEip:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Join [ "-", ["linux",!Ref LinuxEnvironmentType,"eip-management"]]

Outputs:

  LinuxEipManagementAllocationId:
    Description: Management AllocationId
    Value: !GetAtt LinuxManagementEip.AllocationId
    Export:
      Name: !Join [ "-", ["linux-cf-l3",!Ref LinuxEnvironmentType,"LinuxEipManagementAllocationId"]]