# Stack name: linux-cf-sgs-
AWSTemplateFormatVersion: 2010-09-09
Description: "Linux: Security Groups"

Parameters:

  LinuxEnvironmentType:
    Type: String

  LinuxSecurityGroupIngressManagementIp:
    Type: String

  LinuxVpcVpcId:
    Type: String

Mappings:

  Instances:
    management:
      name: "kali"

Resources:

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
  LinuxManagementSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ "-", ["linux",!Ref LinuxEnvironmentType,!FindInMap [Instances, management, name]]]
      VpcId: !Ref LinuxVpcVpcId
      GroupDescription: "Allow ingress traffic on SSH from static IPs"
      SecurityGroupIngress:
        - CidrIp: !Ref LinuxSecurityGroupIngressManagementIp
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: "Name"
          Value: !Join [ "-", ["linux",!Ref LinuxEnvironmentType,!FindInMap [Instances, management, name]]]

Outputs:

  LinuxManagementSecurityGroupId:
    Description: HTTP security group ID
    Value: !Ref LinuxManagementSecurityGroup
    Export:
      Name: !Join [ "-", ["linux-cf-instances",!Ref LinuxEnvironmentType,"LinuxManagementSecurityGroupId"]]
